FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build --prod


FROM nginx:stable-alpine
COPY --from=builder /app/dist/notes /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]